class Game {
  final String id;
  final String title;
  final String genreId;
  final double rating;
  final String description;
  final int year;
  final String platform;

  const Game({
    required this.id,
    required this.title,
    required this.genreId,
    required this.rating,
    required this.description,
    required this.year,
    required this.platform,
  });

  // Топ-10 игр для каждого жанра
  static List<Game> getTop10ByGenre(String genreId) {
    final allGames = _getAllGames();
    return allGames
        .where((game) => game.genreId == genreId)
        .toList();
  }

  // Получить игры для нескольких жанров
  static Map<String, List<Game>> getTop10ForGenres(List<String> genreIds) {
    final result = <String, List<Game>>{};
    for (final genreId in genreIds) {
      result[genreId] = getTop10ByGenre(genreId);
    }
    return result;
  }

  static List<Game> _getAllGames() {
    return const [
      // Экшен
      Game(
        id: 'action_1',
        title: 'God of War Ragnarök',
        genreId: 'action',
        rating: 9.5,
        description: 'Эпическое приключение Кратоса и Атрея в мире скандинавской мифологии',
        year: 2022,
        platform: 'PS5, PS4, PC',
      ),
      Game(
        id: 'action_2',
        title: 'Elden Ring',
        genreId: 'action',
        rating: 9.6,
        description: 'Souls-like RPG от FromSoftware в открытом мире',
        year: 2022,
        platform: 'PS5, Xbox, PC',
      ),
      Game(
        id: 'action_3',
        title: 'Spider-Man 2',
        genreId: 'action',
        rating: 9.3,
        description: 'Новые приключения Питера Паркера и Майлза Моралеса',
        year: 2023,
        platform: 'PS5',
      ),
      Game(
        id: 'action_4',
        title: 'Devil May Cry 5',
        genreId: 'action',
        rating: 9.0,
        description: 'Стильный hack and slash с невероятными комбо',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'action_5',
        title: 'Sekiro: Shadows Die Twice',
        genreId: 'action',
        rating: 9.4,
        description: 'Сложный экшен в феодальной Японии',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'action_6',
        title: 'Ghost of Tsushima',
        genreId: 'action',
        rating: 9.2,
        description: 'Самурайская эпопея на острове Цусима',
        year: 2020,
        platform: 'PS5, PS4, PC',
      ),
      Game(
        id: 'action_7',
        title: 'The Last of Us Part II',
        genreId: 'action',
        rating: 9.3,
        description: 'Эмоциональная история мести в постапокалипсисе',
        year: 2020,
        platform: 'PS5, PS4',
      ),
      Game(
        id: 'action_8',
        title: 'Bayonetta 3',
        genreId: 'action',
        rating: 8.8,
        description: 'Безумный экшен с ведьмами и ангелами',
        year: 2022,
        platform: 'Switch',
      ),
      Game(
        id: 'action_9',
        title: 'Metal Gear Rising',
        genreId: 'action',
        rating: 8.9,
        description: 'Кибер-ниндзя рубит всё подряд',
        year: 2013,
        platform: 'Multi',
      ),
      Game(
        id: 'action_10',
        title: 'Astro Bot',
        genreId: 'action',
        rating: 9.1,
        description: 'Очаровательный платформер для PS5',
        year: 2024,
        platform: 'PS5',
      ),

      // RPG
      Game(
        id: 'rpg_1',
        title: 'Baldur\'s Gate 3',
        genreId: 'rpg',
        rating: 9.7,
        description: 'Лучшая RPG современности по D&D',
        year: 2023,
        platform: 'PC, PS5, Xbox',
      ),
      Game(
        id: 'rpg_2',
        title: 'The Witcher 3',
        genreId: 'rpg',
        rating: 9.8,
        description: 'Эпическое приключение Геральта из Ривии',
        year: 2015,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_3',
        title: 'Final Fantasy XVI',
        genreId: 'rpg',
        rating: 8.9,
        description: 'Новая часть легендарной серии',
        year: 2023,
        platform: 'PS5, PC',
      ),
      Game(
        id: 'rpg_4',
        title: 'Persona 5 Royal',
        genreId: 'rpg',
        rating: 9.5,
        description: 'JRPG о ворах-призраках в Токио',
        year: 2020,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_5',
        title: 'Divinity: Original Sin 2',
        genreId: 'rpg',
        rating: 9.4,
        description: 'Тактическая RPG с невероятной свободой',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_6',
        title: 'Dragon Age: Inquisition',
        genreId: 'rpg',
        rating: 8.8,
        description: 'Спасите мир от демонов',
        year: 2014,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_7',
        title: 'Mass Effect Legendary',
        genreId: 'rpg',
        rating: 9.2,
        description: 'Космическая сага о команде Шепарда',
        year: 2021,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_8',
        title: 'Cyberpunk 2077',
        genreId: 'rpg',
        rating: 8.7,
        description: 'Футуристический Найт-Сити',
        year: 2020,
        platform: 'Multi',
      ),
      Game(
        id: 'rpg_9',
        title: 'Starfield',
        genreId: 'rpg',
        rating: 8.5,
        description: 'Космическая RPG от Bethesda',
        year: 2023,
        platform: 'Xbox, PC',
      ),
      Game(
        id: 'rpg_10',
        title: 'Yakuza: Like a Dragon',
        genreId: 'rpg',
        rating: 8.9,
        description: 'JRPG о якудза в Японии',
        year: 2020,
        platform: 'Multi',
      ),

      // Стратегии
      Game(
        id: 'strategy_1',
        title: 'Civilization VI',
        genreId: 'strategy',
        rating: 9.1,
        description: 'Построй свою цивилизацию от древности до космоса',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'strategy_2',
        title: 'XCOM 2',
        genreId: 'strategy',
        rating: 8.9,
        description: 'Тактическая стратегия против инопланетян',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'strategy_3',
        title: 'Total War: Warhammer III',
        genreId: 'strategy',
        rating: 9.0,
        description: 'Эпические сражения в мире Warhammer',
        year: 2022,
        platform: 'PC',
      ),
      Game(
        id: 'strategy_4',
        title: 'StarCraft II',
        genreId: 'strategy',
        rating: 9.3,
        description: 'Легендарная RTS в космосе',
        year: 2010,
        platform: 'PC',
      ),
      Game(
        id: 'strategy_5',
        title: 'Age of Empires IV',
        genreId: 'strategy',
        rating: 8.7,
        description: 'Возрождение классической серии',
        year: 2021,
        platform: 'PC, Xbox',
      ),
      Game(
        id: 'strategy_6',
        title: 'Crusader Kings III',
        genreId: 'strategy',
        rating: 9.2,
        description: 'Средневековая династическая стратегия',
        year: 2020,
        platform: 'PC',
      ),
      Game(
        id: 'strategy_7',
        title: 'Fire Emblem: Three Houses',
        genreId: 'strategy',
        rating: 8.9,
        description: 'Тактическая JRPG с выбором судьбы',
        year: 2019,
        platform: 'Switch',
      ),
      Game(
        id: 'strategy_8',
        title: 'Into the Breach',
        genreId: 'strategy',
        rating: 8.8,
        description: 'Тактика с гигантскими роботами',
        year: 2018,
        platform: 'Multi',
      ),
      Game(
        id: 'strategy_9',
        title: 'Company of Heroes 3',
        genreId: 'strategy',
        rating: 8.5,
        description: 'RTS о Второй мировой войне',
        year: 2023,
        platform: 'PC',
      ),
      Game(
        id: 'strategy_10',
        title: 'Frostpunk',
        genreId: 'strategy',
        rating: 8.9,
        description: 'Стратегия выживания в замёрзшем мире',
        year: 2018,
        platform: 'Multi',
      ),

      // Хорроры
      Game(
        id: 'horror_1',
        title: 'Resident Evil Village',
        genreId: 'horror',
        rating: 9.0,
        description: 'Хоррор в таинственной деревне',
        year: 2021,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_2',
        title: 'Dead Space Remake',
        genreId: 'horror',
        rating: 9.1,
        description: 'Космический хоррор на корабле USG Ishimura',
        year: 2023,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_3',
        title: 'Silent Hill 2 Remake',
        genreId: 'horror',
        rating: 9.3,
        description: 'Психологический хоррор в туманном городе',
        year: 2024,
        platform: 'PS5, PC',
      ),
      Game(
        id: 'horror_4',
        title: 'Amnesia: The Bunker',
        genreId: 'horror',
        rating: 8.6,
        description: 'Выживание в бункере Первой мировой',
        year: 2023,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_5',
        title: 'The Callisto Protocol',
        genreId: 'horror',
        rating: 8.3,
        description: 'Хоррор на спутнике Юпитера',
        year: 2022,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_6',
        title: 'Outlast 2',
        genreId: 'horror',
        rating: 8.7,
        description: 'Побег от религиозных фанатиков',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_7',
        title: 'Alien: Isolation',
        genreId: 'horror',
        rating: 9.0,
        description: 'Прячься от Чужого на космической станции',
        year: 2014,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_8',
        title: 'Layers of Fear',
        genreId: 'horror',
        rating: 8.2,
        description: 'Психологический хоррор о безумном художнике',
        year: 2023,
        platform: 'Multi',
      ),
      Game(
        id: 'horror_9',
        title: 'Alan Wake 2',
        genreId: 'horror',
        rating: 9.2,
        description: 'Триллер о писателе в кошмарном мире',
        year: 2023,
        platform: 'PS5, Xbox, PC',
      ),
      Game(
        id: 'horror_10',
        title: 'Little Nightmares II',
        genreId: 'horror',
        rating: 8.8,
        description: 'Атмосферный хоррор-платформер',
        year: 2021,
        platform: 'Multi',
      ),

      // Шутеры
      Game(
        id: 'shooter_1',
        title: 'Call of Duty: Modern Warfare III',
        genreId: 'shooter',
        rating: 8.5,
        description: 'Военный шутер с кампанией и мультиплеером',
        year: 2023,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_2',
        title: 'Counter-Strike 2',
        genreId: 'shooter',
        rating: 9.0,
        description: 'Легендарный тактический шутер',
        year: 2023,
        platform: 'PC',
      ),
      Game(
        id: 'shooter_3',
        title: 'Valorant',
        genreId: 'shooter',
        rating: 8.8,
        description: 'Тактический шутер 5v5 с агентами',
        year: 2020,
        platform: 'PC',
      ),
      Game(
        id: 'shooter_4',
        title: 'Apex Legends',
        genreId: 'shooter',
        rating: 8.7,
        description: 'Королевская битва с легендами',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_5',
        title: 'DOOM Eternal',
        genreId: 'shooter',
        rating: 9.2,
        description: 'Брутальный шутер против демонов',
        year: 2020,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_6',
        title: 'Halo Infinite',
        genreId: 'shooter',
        rating: 8.6,
        description: 'Мастер Чиф возвращается',
        year: 2021,
        platform: 'Xbox, PC',
      ),
      Game(
        id: 'shooter_7',
        title: 'Destiny 2',
        genreId: 'shooter',
        rating: 8.8,
        description: 'MMO-шутер в космосе',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_8',
        title: 'Titanfall 2',
        genreId: 'shooter',
        rating: 9.3,
        description: 'Шутер с меха-роботами',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_9',
        title: 'Borderlands 3',
        genreId: 'shooter',
        rating: 8.5,
        description: 'Безумный лутер-шутер',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'shooter_10',
        title: 'Overwatch 2',
        genreId: 'shooter',
        rating: 8.4,
        description: 'Командный шутер с героями',
        year: 2022,
        platform: 'Multi',
      ),

      // Инди
      Game(
        id: 'indie_1',
        title: 'Hades',
        genreId: 'indie',
        rating: 9.5,
        description: 'Roguelike о побеге из подземного мира',
        year: 2020,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_2',
        title: 'Hollow Knight',
        genreId: 'indie',
        rating: 9.4,
        description: 'Metroidvania в мире насекомых',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_3',
        title: 'Celeste',
        genreId: 'indie',
        rating: 9.3,
        description: 'Платформер о преодолении себя',
        year: 2018,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_4',
        title: 'Stardew Valley',
        genreId: 'indie',
        rating: 9.2,
        description: 'Фермерский симулятор с душой',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_5',
        title: 'Undertale',
        genreId: 'indie',
        rating: 9.1,
        description: 'RPG где никого не нужно убивать',
        year: 2015,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_6',
        title: 'Dead Cells',
        genreId: 'indie',
        rating: 9.0,
        description: 'Roguelike метroidvania',
        year: 2018,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_7',
        title: 'Cuphead',
        genreId: 'indie',
        rating: 8.9,
        description: 'Сложный платформер в стиле 30-х',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_8',
        title: 'Ori and the Will of the Wisps',
        genreId: 'indie',
        rating: 9.3,
        description: 'Красивейший платформер',
        year: 2020,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_9',
        title: 'Disco Elysium',
        genreId: 'indie',
        rating: 9.6,
        description: 'Детективная RPG о самопознании',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'indie_10',
        title: 'Terraria',
        genreId: 'indie',
        rating: 9.1,
        description: '2D песочница с крафтингом',
        year: 2011,
        platform: 'Multi',
      ),

      // Симуляторы
      Game(
        id: 'simulator_1',
        title: 'Microsoft Flight Simulator',
        genreId: 'simulator',
        rating: 9.2,
        description: 'Реалистичный симулятор полётов',
        year: 2020,
        platform: 'PC, Xbox',
      ),
      Game(
        id: 'simulator_2',
        title: 'Euro Truck Simulator 2',
        genreId: 'simulator',
        rating: 8.8,
        description: 'Езди на грузовике по Европе',
        year: 2012,
        platform: 'PC',
      ),
      Game(
        id: 'simulator_3',
        title: 'The Sims 4',
        genreId: 'simulator',
        rating: 8.5,
        description: 'Создавай и управляй жизнями симов',
        year: 2014,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_4',
        title: 'Cities: Skylines',
        genreId: 'simulator',
        rating: 9.0,
        description: 'Построй свой идеальный город',
        year: 2015,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_5',
        title: 'Planet Coaster',
        genreId: 'simulator',
        rating: 8.7,
        description: 'Создай парк развлечений мечты',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_6',
        title: 'Farming Simulator 22',
        genreId: 'simulator',
        rating: 8.3,
        description: 'Стань настоящим фермером',
        year: 2021,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_7',
        title: 'Assetto Corsa Competizione',
        genreId: 'simulator',
        rating: 8.9,
        description: 'Реалистичный автосимулятор',
        year: 2019,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_8',
        title: 'Kerbal Space Program',
        genreId: 'simulator',
        rating: 9.1,
        description: 'Построй ракету и лети в космос',
        year: 2015,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_9',
        title: 'Two Point Hospital',
        genreId: 'simulator',
        rating: 8.6,
        description: 'Управляй больницей',
        year: 2018,
        platform: 'Multi',
      ),
      Game(
        id: 'simulator_10',
        title: 'PowerWash Simulator',
        genreId: 'simulator',
        rating: 8.8,
        description: 'Медитативная мойка всего подряд',
        year: 2022,
        platform: 'Multi',
      ),

      // Приключения
      Game(
        id: 'adventure_1',
        title: 'The Legend of Zelda: TOTK',
        genreId: 'adventure',
        rating: 9.8,
        description: 'Эпическое приключение в Хайруле',
        year: 2023,
        platform: 'Switch',
      ),
      Game(
        id: 'adventure_2',
        title: 'Red Dead Redemption 2',
        genreId: 'adventure',
        rating: 9.7,
        description: 'Жизнь ковбоя на Диком Западе',
        year: 2018,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_3',
        title: 'Uncharted 4',
        genreId: 'adventure',
        rating: 9.4,
        description: 'Последнее приключение Нейтана Дрейка',
        year: 2016,
        platform: 'PS4, PS5, PC',
      ),
      Game(
        id: 'adventure_4',
        title: 'Horizon Forbidden West',
        genreId: 'adventure',
        rating: 9.1,
        description: 'Элой исследует запретный запад',
        year: 2022,
        platform: 'PS5, PS4, PC',
      ),
      Game(
        id: 'adventure_5',
        title: 'Tomb Raider (2013)',
        genreId: 'adventure',
        rating: 8.9,
        description: 'Перезапуск серии о Ларе Крофт',
        year: 2013,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_6',
        title: 'A Plague Tale: Requiem',
        genreId: 'adventure',
        rating: 8.8,
        description: 'Путешествие брата и сестры',
        year: 2022,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_7',
        title: 'Life is Strange',
        genreId: 'adventure',
        rating: 8.9,
        description: 'История о путешествии во времени',
        year: 2015,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_8',
        title: 'What Remains of Edith Finch',
        genreId: 'adventure',
        rating: 9.0,
        description: 'Семейные истории рода Финчей',
        year: 2017,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_9',
        title: 'Firewatch',
        genreId: 'adventure',
        rating: 8.5,
        description: 'Тайна в лесах Вайоминга',
        year: 2016,
        platform: 'Multi',
      ),
      Game(
        id: 'adventure_10',
        title: 'Journey',
        genreId: 'adventure',
        rating: 9.2,
        description: 'Медитативное путешествие через пустыню',
        year: 2012,
        platform: 'PS4, PC',
      ),
    ];
  }
}
